### ISSUE TITLE
关于webvision数据集的疑问

### ISSUE THREAD

**Issue by PunkMale** [MacLLL/SELC#3]
作者您好！
我刚刚接触WebVision数据集。
关于[WebVision Dataset](https://data.vision.ee.ethz.ch/cvl/webvision/download.html)数据集我有两个问题：
1. WebVision 1 中有`Resized Images (small version)` 和 `Original Images` 两种分类，请问这两种分类是否仅仅是数据尺寸（或者说质量）不一样，图片和标签的是否都和[Flicker Images Metadata](https://data.vision.ee.ethz.ch/cvl/webvision/flickr_meta.tar)、[Google Images Metadata](https://data.vision.ee.ethz.ch/cvl/webvision/google_meta.tar)一一对应？
2. 请问您和其他研究者一般使用`Resized Images (small version)` 还是 `Original Images` ？
感谢您的回复！
<img width="656" alt="image" src="https://github.com/MacLLL/SELC/assets/44804926/0e5fe0f9-f9bd-4867-9305-8b834dc851c8">

**Comment by MacLLL** [comment]
1. 依然是对齐的。
2. 用resized images。

**Comment by PunkMale** [comment]
好的，非常感谢您的解答！🙏
